buildJob:
  stage: build
  script:
    mkdir build; cd build; cmake -G "Unix Makefiles" .. ; make; cp -r ../Resources/* ChessEngine/;cp -r ../Resources/* UnitTesting/
  artifacts:
    paths: 
      - build/UnitTesting
    expire_in: 30 min
testing:
  stage: test
  script:
    cd build/UnitTesting/; ./UnitTests