buildJob:
  stage: build
  script:
    mkdir build; cd build; cmake -G "Unix Makefiles" .. ; make
  artifacts:
    paths: 
      - build/UnitTesting/UnitTests
    expire_in: 30 min
testing:
  stage: test
  script:
    cd build/UnitTesting/; ./UnitTests