buildJob:
  stage: build
  script:
    mkdir build; cd build; cmake -G "Unix Makefiles" .. ; make
  artifacts:
    paths: 
      - build/ChessEngine/ChessEngine
testing:
  stage: test
  script:
    cd Build/UnitTesting/; ./UnitTests